### ISSUE TITLE
Unexpected keyword argument

### ISSUE THREAD

**Issue by Oloshka** [jeffball55/rop_compiler#2]
When I try to run rsync.py from pyrop/example folder I got:

```
Starting rsync with the exploit payload
Traceback (most recent call last):
  File "rsync.py", line 32, in <module>
    p = process(argv = [filename, '-r', '--exclude-from=/tmp/payload', '.', '/tmp/to/'], executable = filename) 
TypeError: __init__() got an unexpected keyword argument 'argv'
```

**Comment by jeffball55** [comment]
Hmm, it looks like the process function is defined with a different `__init__` constructor than the one on my computer.  Where did you install pwntools from?  Can you run `help(process.__init__)` in python and see what the arguments to process are supposed to be named?  That line is just starting rsync with the specified arguments.

When I run the example on my computer it works.  Here is what pwntools on my machine says the arguments to process's constructor should be named:

```
$ python -c 'from pwn import *; help(process.__init__)'
Help on method __init__ in module pwnlib.tubes.process:

__init__(self, argv, shell=False, executable=None, cwd=None, env=None, timeout=pwnlib.timeout.Timeout.default, stdin=-1, stdout=<object object>, stderr=-2, close_fds=True, preexec_fn=<function <lambda>>) unbound pwnlib.tubes.process.process method
```

**Comment by Oloshka** [comment]
Output of `help(process.__init__)`:

```
Help on method __init__ in module pwnlib.tubes.process:

__init__(self, args, shell=False, executable=None, cwd=None, env=None, timeout=pwnlib.timeout.Timeout.default) unbound pwnlib.tubes.process.process method
```

I installed pwntools version 2.2 by `pip install pwntools`. 
After some investigation I realized that all works fine with latest version (2.2.0) installed from github repo.

**Comment by jeffball55** [comment]
I also installed mine from the github repo.  I didn't realize the pip source was old.  I'll add a note to the dependency list.  Thanks.
